# volumes:
#   app-code:
#     driver_opts:
#       type: "nfs"
#       o: "rw"
#       device: "./app/"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html/
  
  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./app:/var/www/html/
    